### ISSUE TITLE
Error while loading graph to AMC block

### ISSUE THREAD

**Issue by dandrspc** [gnuradio/gr-inspector#30]
I'm using Ubuntu 18.04, tensorflow 0.12.1 but i'm getting this error while loading the graph. 

Loading: "/home/dandrspc/default/src/gr-inspector/examples/amc_cnn.grc"
>>> Done

Generating: '/home/dandrspc/default/src/gr-inspector/examples/top_block.py'

Executing: /usr/bin/python2 -u /home/dandrspc/default/src/gr-inspector/examples/
top_block.py

Traceback (most recent call last):
  File "/home/dandrspc/default/src/gr-inspector/examples/top_block.py", line 142
, in <module>
    main()
  File "/home/dandrspc/default/src/gr-inspector/examples/top_block.py", line 130
, in main
    tb = top_block_cls()
  File "/home/dandrspc/default/src/gr-inspector/examples/top_block.py", line 76,
 in __init__
    self.inspector_tfmodel_vcf_0 = inspector.tfmodel_vcf("complex64",128,'/home/
dandrspc/Documentos/signal intelligence/examples-master/modulation_recognition/c
nn_/00000002',(),0)
  File "/home/dandrspc/default/lib/python2.7/dist-packages/inspector/tfmodel_vcf
.py", line 64, in __init__
    sess, inp, out,classes = self.load_graph(graphfile)
  File "/home/dandrspc/default/lib/python2.7/dist-packages/inspector/tfmodel_vcf
.py", line 80, in load_graph
    output_graph_path)
  File "/home/dandrspc/.local/lib/python2.7/site-packages/tensorflow/contrib/ses
sion_bundle/session_bundle.py", line 86, in load_session_bundle_from_path
    "Expected exactly one serving GraphDef in : %s" % meta_graph_def)
RuntimeError: Expected exactly one serving GraphDef in : meta_info_def {
  stripped_op_list {
    op {
      name: "Add"
      input_arg {
        name: "x"
        type_attr: "T"
      }
      input_arg {
        name: "y"
        type_attr: "T"
      }
.
.
.
.

**Comment by sbmueller** [comment]
Calling for @chrisruk

**Comment by sbmueller** [comment]
@dandrspc did you solve the issue? If so, please share how you solved it in case someone else stumbles upon the same issue.
