### ISSUE TITLE
QT GUI Inspector Sink causes the GRC UI to freeze/crash

### ISSUE THREAD

**Issue by paul-k-young** [gnuradio/gr-inspector#47]
Adding the QT GUI Inspector Sink to a flowgraph (even an empty one) causes the following messages to be repeated, and for the UI to lock up then crash.  The full details can be found in this bug: https://github.com/gnuradio/gnuradio/issues/6452

Traceback (most recent call last):
  File "C:\Users\paulk\radioconda\lib\site-packages\gnuradio\grc\gui\DrawingArea.py", line 223, in draw
    self._flow_graph.draw(cr)
  File "C:\Users\paulk\radioconda\lib\site-packages\gnuradio\grc\gui\canvas\flowgraph.py", line 535, in draw
    draw_element(cr)
  File "C:\Users\paulk\radioconda\lib\site-packages\gnuradio\grc\gui\canvas\block.py", line 280, in draw
    port.draw(cr)
  File "C:\Users\paulk\radioconda\lib\site-packages\gnuradio\grc\gui\canvas\port.py", line 134, in draw
    cr.rectangle(*self._area)
TypeError: Context.rectangle() takes exactly 4 arguments (0 given)

I was able to reproduce this behavior on a Windows radioconda install.  The behavior was observed even after a full upgrade (conda update --all).  None of the core QT GUI components had this issue, so I'm adding a bug here.

**Comment by paul-k-young** [comment]
3.10.5.0 has a slightly different error message (DrawingArea.py has the error on line 222)

  File "C:\Users\paulk\radioconda\lib\site-packages\gnuradio\grc\gui\DrawingArea.py", line 222, in draw
    self._flow_graph.draw(cr)
  File "C:\Users\paulk\radioconda\lib\site-packages\gnuradio\grc\gui\canvas\flowgraph.py", line 535, in draw
    draw_element(cr)
  File "C:\Users\paulk\radioconda\lib\site-packages\gnuradio\grc\gui\canvas\block.py", line 280, in draw
    port.draw(cr)
  File "C:\Users\paulk\radioconda\lib\site-packages\gnuradio\grc\gui\canvas\port.py", line 134, in draw
    cr.rectangle(*self._area)
TypeError: Context.rectangle() takes exactly 4 arguments (0 given)

**Comment by paul-k-young** [comment]
Update - the GRC code wasn't gracefully handling some canvas params that were being passed as ints (it only worked for strings).  I'm not sure whether that's an issue with the block or with grc, although I have a PR for grc pending.
